# Base information
baseURL = "https://vedacomputing-3d1f5.web.app"
languageCode = "en-gb"
title = "Gustavo Cabezal Blog and Portfolio"
theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=4


[params]
home = "Home"
# Meta data
description = "The website of Gustavo Cabezal aka VedaComputing. Developer, Administrator, Creator and Teacher."
author = "Gustavo Cabezal"


  [params.contact]
  enable = false
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "vedacomputing@gmail.com"
  address = ""
  googlemaps = ""

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

